# Generated by Django 3.0.8 on 2022-02-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarymodel',
            old_name='texth',
            new_name='text',
        ),
    ]
