# Generated by Django 3.0.8 on 2022-02-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0005_diarymodel_datesave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarymodel',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
